# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65ee7d00673ca61b647c7329f7d8f06582b71e923315c4832fdf956efc4d8c2f0b937870c41efbb92c2e778580d851a273ed7dd78629f838aa2e3ce9d0a5be63

test:
  secret_key_base: 8afad955426875c3a436cb486fb36c0e86bf4567563fc903c570ff029eeb4245680229e5bd595c01a26a2aa756e3f669d538f58fd83988a18bb4a421930d1e7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
